# Generated by Django 3.2.4 on 2021-06-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flour_type', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='person',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='taste',
        ),
        migrations.AddField(
            model_name='topping',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='pizza',
            name='dough_flour',
            field=models.ForeignKey(default='white', on_delete=django.db.models.deletion.CASCADE, to='pizzaOrder.flour', to_field='flour_type'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrder.order'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.ForeignKey(default='tomato', on_delete=django.db.models.deletion.CASCADE, to='pizzaOrder.sauce', to_field='sauce_name'),
        ),
    ]
