# Generated by Django 3.2.4 on 2021-07-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0002_auto_20210629_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flour',
            old_name='flour_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sauce',
            old_name='sauce_name',
            new_name='name',
        ),
    ]
