# Generated by Django 3.2.4 on 2021-07-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0003_auto_20210704_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='pizzaOrder.Topping'),
        ),
    ]
