# Generated by Django 3.2.4 on 2021-07-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0004_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='pizzaOrder.Topping'),
        ),
    ]
